name: ADrelease
on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: blackmatrix7-ios_rule_script
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync blackmatrix7-ios_rule_script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/blackmatrix7/ios_rule_script.git"
          source_branch: "release"
          destination_branch: "ADrelease"
          github_token: ${{ secrets.PAT }}
